export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DROP_FROM_CART = 'DROP_FROM_CART'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_FULFILLED = 'FETCH_PRODUCTS_FULFILLED'
export const FETCH_PRODUCTS_REJECTED = 'FETCH_PRODUCTS_REJECTED'

export const FETCH_RECIPES = 'FETCH_RECIPES'
export const FETCH_RECIPES_FULFILLED = 'FETCH_RECIPES_FULFILLED'
export const FETCH_RECIPES_REJECTED = 'FETCH_RECIPES_REJECTED'

export const FETCH_ARTICLES = 'FETCH_ARTICLES'
export const FETCH_ARTICLES_FULFILLED = 'FETCH_ARTICLES_FULFILLED'
export const FETCH_ARTICLES_REJECTED = 'FETCH_ARTICLES_REJECTED'


